### ISSUE TITLE
cannot call method 'register'

### ISSUE THREAD

**Issue by shokai** [mizchi/hue-command#1]
```
% hue register
TypeError: Cannot call method 'register' of null
  at Object.<anonymous> (/usr/local/lib/node_modules/hue-command/api.js:102:9)
  at Object.<anonymous> (/usr/local/lib/node_modules/hue-command/api.js:114:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/hue-command/bin/hue:4:9)
  at Object.<anonymous> (/usr/local/lib/node_modules/hue-command/bin/hue:25:4)
  at Module._compile (module.js:456:26)
```

**Comment by mizchi** [comment]
なんかそこ自分で使ってても怪しかったですね。直しときます。
work aroundとして次のファイルを ~/.hue.json に保存すれば動くはずです…がその前に他の方法でどうにかして usernameとipを取得する必要があります。

```
{
  "username": ".....",
  "ip": 192.168.11.xxx"
}
```
